// AUTH TYPES
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const DEACTIVATE_SUCCESS = 'DEACTIVATE_SUCCESS';
export const AUTH_INIT = 'AUTH_INIT';

// ACCOUNT TYPES
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_LOADED = 'ACCOUNTS_LOADED';
export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';
export const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR';

//  TRANSCATION TYPES
export const TRANSCATION_LOADING = 'TRANSCATION_LOADING';
export const TRANSCATION_LOADED = 'TRANSCATION_LOADED';
export const TRANSCATION_CREATED = 'TRANSCATION_CREATED';
export const TRANSCATION_DELETED = 'TRANSCATION_DELETED';
export const TRANSCATION_UPDATED = 'TRANSCATION_UPDATED';
export const TRANSCATION_ERROR = 'TRANSCATION_ERROR';