version: '3'
services:

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/joan/home/docker/data/redis:/data

  mongodb:
    image: mongo:3.6.1
    container_name: bookmongodb
    volumes:
      - /Users/joan/home/docker/data/mongodb:/data/db
      - /Users/joan/home/docker/config:/data/configdb
    ports:
        - 27017:27017
    command: mongod